extends:
  - stylelint-config-sugarss-recommended
ignoreFiles:
  - .nuxt/**/*
  - node_modules/**/*
plugins:
  - stylelint-scss
rules:{{#if_eq lint_rule true}}
  declaration-block-no-redundant-longhand-properties: # 省略可能な記法を使用する
    - true
    - ignoreShorthands:
      - "/grid/"
  font-family-name-quotes: always-where-recommended # Font名のクォーテーションを省略する
  font-weight-notation: numeric # フォント名を文字列で指定する
  function-url-quotes: never # url()などの引数ではクォーテーションを省略する
  indentation: null # インデントの警告を無視
  max-line-length: null # １行の文字数を制限しない
  no-unknown-animations: null # Vueによってハッシュが割り当てられるので無効化
  number-leading-zero: always # 小数の最初の0を省略させない
  selector-list-comma-newline-after: null # 複数セレクタのカンマの後にスペースを入れるか{{/if_eq}}
